### ISSUE TITLE
Camera opened but scan not working

### ISSUE THREAD

**Issue by nandhakumar0026** [bear2b/bear_sdk_demo_ios#1]
Hi ,

I have implemented the normal scan like below,

camera opened , but the scan didn't start.

i am getting the reachable correctly,

```
reachabilityStatusChanged: reachable = 1
```

```

- (IBAction)showBearScanner {
    
    NoStoryboardViewController* vc = [[NoStoryboardViewController alloc] init];
    
    [vc setDelegate:vc];
    
    [vc setScannerColor:[UIColor whiteColor]];
    
    [vc setTimeToPause:10];
        
    [self showViewController:vc sender:self];
}
```

kindly check and let me know your comments ,

FYI : i tried like -> if i call the method in my viewcontroller-> viewdidload

`[self.handler startScanning];` getting error only

Thank you.

**Comment by GenChe** [comment]
Hi @nandhakumar0026 ,
could you provide which exact error have you received (error code or description)? Looks like something wrong with `secretKey`.

**Comment by nandhakumar0026** [comment]
Hi @GenChe ,

now i called the method `[self.handler startScanning];` on `viewdidappear`
, its woking good.

Thank you.
