### ISSUE TITLE
Xcode 10.1 / Swift 4.2.1 support

### ISSUE THREAD

**Issue by cyrille-legrand** [bear2b/bear_sdk_demo_ios#2]
Bear is currently compiled with Xcode 10.0 and Swift 4.1.2
Cannot be used with Xcode 10.1 and a Swift 4.2(.1) project as-is.

**Comment by GenChe** [comment]
Hello @cyrille-legrand. Yes, you are right. Version compatible with Xcode 10.1/Swift 4.2.1 will be released soon.

**Comment by cyrille-legrand** [comment]
Version 2.0.11 works fine with Xcode 10.1, thanks!
