### ISSUE TITLE
Crash on BearSDK.setSecretKey

### ISSUE THREAD

**Issue by savage7** [bear2b/bear_sdk_demo_ios#4]
We have an app running with Sdk Version 2.2. I wanted to upgrade this app with 3.0 and had a problem, that the app crashes when I start the ARViewController.

To simplify the test I created an example app with a very basic setup, but this example app already crashes when initializing the app. The main difference is that I use **cocoapods** and not carthage, your sample works.

When I call "BearSDK.setSecretKey" the app crashes. Seams to be some kind of threading issue in your ReachabilityService.init()

Please find attached a testproject:
[Archiv.zip](https://github.com/bear2b/bear_sdk_demo_ios/files/4485727/Archiv.zip)
Screenshot from the crash:
![Bildschirmfoto 2020-04-16 um 10 22 43](https://user-images.githubusercontent.com/971353/79432676-7323bf80-7fcc-11ea-87d8-7905c6c39d13.png)

**Comment by GenChe** [comment]
Hello @savage7,

Thank you for the bug report, we've reproduced and identified this issue. We will work on bug fix this week and will be back with news soon.

**Comment by GenChe** [comment]
@savage7, I come back to you with the good news - threading issue has been fixed and [new BearSDK version 3.0.1](https://github.com/bear2b/bear_sdk_demo_ios/releases/tag/3.0.1) is already available. You are welcome to check it on your side and close the issue if it works fine for you.

**Comment by savage7** [comment]
@GenChe Tested it, crash is fixed. thxs
