### ISSUE TITLE
Regular crash on latest version

### ISSUE THREAD

**Issue by savage7** [bear2b/bear_sdk_demo_ios#6]
![bear_sdk_crash](https://user-images.githubusercontent.com/971353/83637378-d59a4480-a5a7-11ea-82b2-536c6e2b87cd.png)
![event](https://user-images.githubusercontent.com/971353/83637414-e21e9d00-a5a7-11ea-936d-2a787b754e7f.png)

I've debugged this forever because I thought this is an internal problem in our app. 
I start the app and let it run for some time ~5min, then the SDK crashes. See the logs attached.
You seam to .bind() an Oberveable which errors. Please check all your binding if there is correct error handling.

**Comment by GenChe** [comment]
Hello @savage7, thank you for the bug report. We'll look at it during the next few weeks.
