### ISSUE TITLE
Crash when init custom ARViewController from storyboard - using CocoaPods

### ISSUE THREAD

**Issue by Leloo** [bear2b/bear_sdk_demo_ios#8]
I am unable to get an ARViewController instance. There is a crash when i'm trying to do it. 
At first I thought it was a problem in our project, but I created a new project to see if it works on a clean project. Unfortunately, the problem also occurs on the new project. 
We are using CocoaPods, Xcode 11.4.1

This problem began after updating the library to version 3.0.3.
How can we resolve this problem?

Clear implementation:

**`class ScanViewController: ARViewController {
   ///
}`**

![Screenshot 2020-07-02 at 17 50 00](https://user-images.githubusercontent.com/13365059/86381976-e9f85c80-bc8d-11ea-9f2f-6330bda9525c.png)

![Screenshot 2020-07-02 at 17 50 44](https://user-images.githubusercontent.com/13365059/86382138-f7ade200-bc8d-11ea-9c98-ac6f4263202c.png)

**Comment by mmerlangeRA** [comment]
Hi Leloo,
Could you please contact us so that we can discuss and be sure to reproduce on your environment?
Contact is eugene@ar-go.co
Thanks for your help,
Regards,
Michaël

**Comment by Leloo** [comment]
@mmerlangeRA I wrote you an email on eugene@ar-go.co

**Comment by GenChe** [comment]
@Leloo thank you for the report
our development team will check it out and contact you as soon as possible

**Comment by vovnit** [comment]
Hello @Leloo,
I can reproduce your problem only if I'm trying to access `ARViewController` without setting `BearSDK.setSecretKey` first.
Tell me if you're already doing it and the problem persists

**Comment by Leloo** [comment]
Hello @vovnit 
You were right about the secret key setting. The setSecretKey method returns an exception for each of my keys. These keys worked in previous versions of the library.

dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})))

**Comment by vovnit** [comment]
@Leloo we'll contact you shortly to provide working keys, thank you for reaching out

**Comment by paddoum** [comment]
Hello,

Can you liaise with Rodolphe to make sure this customer is entitled to have a key.

thx
P.

Pierre Addoum
CEO & Co-founder
+33 651 605 274

**Comment by paddoum** [comment]
Hi,

He/she is a dev working with our partner Taptic (for our client Opera de
Paris).

Rodolphe

—
*Rodolphe Denoix*
Account Manager
Mobile: +33 6 72 45 66 84
Email: rodolphe@ar-go.co
<http://www.ar-go.co/>
<https://www.linkedin.com/company/ar-go/>
<https://twitter.com/argo_group_news>
<https://www.facebook.com/argo.group.news/>
www.ar-go.co
At ARGO we reach both physical and digital worlds. Discover our brands :
Bear2b <http://bear2b.com/> and SnapPress <http://snappress.fr/>.
ARGO, Station F, 55 Boulevard Vincent Auriol, 75013 Paris

**Comment by paddoum** [comment]
Perfect, sorry Leloo I wasn't sure :-)
